### ISSUE TITLE
pypyr v5 API update

### ISSUE THREAD

**Issue by yaythomas** [python-proman/versioning#1]
`proman_versioning/templates/pypr_hooks.j2` calls the pypyr API - please be aware that as of v5.0 there are some breaking changes in the API. 

If you are still using this functionality, you probably want to amend the file as follows:
```j2
#!{{ python_executable }}
# -*- coding: utf-8 -*-
# copyright: (c) 2020 by Jesse Johnson.
# license: Apache 2.0, see LICENSE for more details.
'''Test git hooks pipeline.'''
from pathlib import Path
import shlex

from git import Repo
from pypyr import log, pipelinerunner

git_repo = Repo('.git', search_parent_directories=True)
git_root_path = git_repo.git.rev_parse('--show-toplevel')

log.logger.set_root_logger(
    log_level={{ log_level }},
    log_path={% if log_path %}'{{ log_path }}'{% else %}None{% endif %}
)

pipelinerunner.run(
    pipeline_name=Path(git_root_path, '.git-hooks'),
    args_in=shlex.split('{{ pipeline_context_input }}'),
    groups=[
        {%- for group in groups -%}
            '{{ group }}'{% if not loop.last %}, {% endif %}
        {%- endfor -%}
    ],
    success_group='{{ success_group }}',
    failure_group='{{ failure_group }}',
)
```

summary of changes:
- `main()` replaced with `run()`
- `pipeline_context_input` replaced by `args_in`
  - note that `args_in` takes a shlex-ed list of str, rather than just the str.
- `working_dir` removed. pypyr will automatically add the pipeline's parent directory to the custom module resolution path for you. 
  - if your `.git-hooks` pipeline is in $PWD, you don't even need to do the `pipeline_name=Path(git_root_path, '.git-hooks'),`, you could just have `pipeline_name='.git-hooks',` as before and it'll work fine.

Release notes + upgrade guide here https://pypyr.io/updates/releases/v5.0.0/.

Hope this helps! Feel free to let me know if you have questions! 😄

**Comment by kuwv** [comment]
Howdy @yaythomas,

I had prototyped multiple ideas in this repo, and I'm moving some pieces into other shared libraries at the moment. Probably going to take some time to complete, but once I finish I can take a look. Changes make sense though.

Part of what I was going to use pypyr was for creating multiple versioning workflows.

Thanks for the heads up and appreciate pypyr!

**Comment by yaythomas** [comment]
Very interested to see where you take it, when the time comes! ...and it course if you have questions or ideas re pypyr feel free to let me know!

**Comment by kuwv** [comment]
This capability will be implemented in another repo. Closing this for now.
